services:
  hbase-docker:
    image: dajobe/hbase:latest
    ports:
      - "2181:2181"
      - "8080:8080"
      - "8085:8085"
      - "9090:9090"
      - "9095:9095"
      - "16020:16010"
    environment:
      - HBASE_DOCKER_HOSTNAME=hbase-docker
#      - HOSTNAME=hbase-docker
    volumes:
      - hbase_data:/data

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=steam_data
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  hbase_data:
  mysql_data: