services:
  spark3.5.2:
    image: bitnami/spark:latest
    container_name: spark3.5.2
    ports:
      - "8080:8080"
      - "7077:7077"
      - "11451:11451"
      - "5000:5000"
    environment:
      - SPARK_SSL_NEED_CLIENT_AUTH=no
      - PYSPARK_PYTHON=/opt/bitnami/python/bin/python3
    volumes:
      # - ./mount/data:/opt/bitnami/spark/data
      - /home/orician/workspace/big_data/Steam-Data-Analysis:/app
    networks:
      - bigdata_net
  
  hive4:
    image: apache/hive:4.0.0
    container_name: hive4
    ports:
      - "10000:10000"
      - "10002:10002"
    environment:
      - SERVICE_NAME=hiveserver2
      - USER=hive
    networks:
      - bigdata_net
      
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=steam_data
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-conf:/etc/mysql/conf.d
    networks:
      - bigdata_net

volumes:
  mysql_data:

networks:
  bigdata_net:
    driver: bridge